// Copyright 1998-2018 Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../DeferredShadingCommon.ush"

Texture2D<float4> AmbientOcclusionTexture;
SamplerState AmbientOcclusionTextureSampler;

void CompositeAmbientOcclusionPS(
	in noperspective float2 UV : TEXCOORD0,
	out float4 OutColor : SV_Target0
)
{
	float4 AmbientOcclusion = AmbientOcclusionTexture.Sample(AmbientOcclusionTextureSampler, UV);
	OutColor = float4(AmbientOcclusion.rgb, 1.0);
}
