// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

#pragma once

/** Versioning */
#define NAVMESHVER_INITIAL				1
#define NAVMESHVER_TILED_GENERATION		2
#define NAVMESHVER_SEAMLESS_REBUILDING_1 3
#define NAVMESHVER_AREA_CLASSES			4
#define NAVMESHVER_CLUSTER_PATH			5
#define NAVMESHVER_SEGMENT_LINKS		6
#define NAVMESHVER_DYNAMIC_LINKS		7
#define NAVMESHVER_64BIT				9
#define NAVMESHVER_CLUSTER_SIMPLIFIED	10
#define NAVMESHVER_OFFMESH_HEIGHT_BUG	11
#define NAVMESHVER_LANDSCAPE_HEIGHT		13


#define NAVMESHVER_LATEST				NAVMESHVER_LANDSCAPE_HEIGHT
#define NAVMESHVER_MIN_COMPATIBLE		NAVMESHVER_LANDSCAPE_HEIGHT
